apiVersion: v1
kind: Pod
metadata:
  name: {{.VspName}}
  namespace: {{.Namespace}}
  labels:
    app: vsp
    dpu-name: {{.DpuName}}
    vendor: mangoboost
spec:
  nodeName: {{.NodeName}}
  nodeSelector:
    kubernetes.io/hostname: {{.NodeName}}
  hostNetwork: true
  hostPID: true
  serviceAccountName: vsp-sa
  terminationGracePeriodSeconds: 180
  restartPolicy: Always
  containers:
  - name: vsp
    image: {{.mangoboost}}
    imagePullPolicy: {{.ImagePullPolicy}}
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - mountPath: /host
      mountPropagation: Bidirectional
      name: host-root
    - mountPath: /var/run/dpu-daemon
      name: vsp-socket
    - mountPath: /sys
      name: sys
    - mountPath: /dev
      name: dev
    - mountPath: /proc
      mountPropagation: Bidirectional
      name: proc
  dnsPolicy: ClusterFirstWithHostNet
  volumes:
  - hostPath:
      path: /proc
      type: ""
    name: proc
  - hostPath:
      path: /sys
      type: ""
    name: sys
  - hostPath:
      path: /dev
      type: ""
    name: dev
  - hostPath:
      path: /var/run/dpu-daemon
      type: DirectoryOrCreate
    name: vsp-socket
  - hostPath:
      path: /
      type: ""
    name: host-root
