//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePlugin) DeepCopyInto(out *ActivePlugin) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePlugin.
func (in *ActivePlugin) DeepCopy() *ActivePlugin {
	if in == nil {
		return nil
	}
	out := new(ActivePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProcessingUnit) DeepCopyInto(out *DataProcessingUnit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProcessingUnit.
func (in *DataProcessingUnit) DeepCopy() *DataProcessingUnit {
	if in == nil {
		return nil
	}
	out := new(DataProcessingUnit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataProcessingUnit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProcessingUnitList) DeepCopyInto(out *DataProcessingUnitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataProcessingUnit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProcessingUnitList.
func (in *DataProcessingUnitList) DeepCopy() *DataProcessingUnitList {
	if in == nil {
		return nil
	}
	out := new(DataProcessingUnitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataProcessingUnitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProcessingUnitSpec) DeepCopyInto(out *DataProcessingUnitSpec) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]DpuCapability, len(*in))
		copy(*out, *in)
	}
	if in.DesiredVFCount != nil {
		in, out := &in.DesiredVFCount, &out.DesiredVFCount
		*out = new(int)
		**out = **in
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(DpuConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProcessingUnitSpec.
func (in *DataProcessingUnitSpec) DeepCopy() *DataProcessingUnitSpec {
	if in == nil {
		return nil
	}
	out := new(DataProcessingUnitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProcessingUnitStatus) DeepCopyInto(out *DataProcessingUnitStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentVFCount != nil {
		in, out := &in.CurrentVFCount, &out.CurrentVFCount
		*out = new(int)
		**out = **in
	}
	if in.Inventory != nil {
		in, out := &in.Inventory, &out.Inventory
		*out = new(DpuInventory)
		(*in).DeepCopyInto(*out)
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(DpuHealth)
		(*in).DeepCopyInto(*out)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProcessingUnitStatus.
func (in *DataProcessingUnitStatus) DeepCopy() *DataProcessingUnitStatus {
	if in == nil {
		return nil
	}
	out := new(DataProcessingUnitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuConfiguration) DeepCopyInto(out *DpuConfiguration) {
	*out = *in
	if in.NetworkMode != nil {
		in, out := &in.NetworkMode, &out.NetworkMode
		*out = new(NetworkMode)
		**out = **in
	}
	if in.StorageOffloadEnabled != nil {
		in, out := &in.StorageOffloadEnabled, &out.StorageOffloadEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecurityPolicyEnabled != nil {
		in, out := &in.SecurityPolicyEnabled, &out.SecurityPolicyEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuConfiguration.
func (in *DpuConfiguration) DeepCopy() *DpuConfiguration {
	if in == nil {
		return nil
	}
	out := new(DpuConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuHealth) DeepCopyInto(out *DpuHealth) {
	*out = *in
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
	if in.TemperatureCelsius != nil {
		in, out := &in.TemperatureCelsius, &out.TemperatureCelsius
		*out = new(int)
		**out = **in
	}
	if in.PowerWatts != nil {
		in, out := &in.PowerWatts, &out.PowerWatts
		*out = new(float64)
		**out = **in
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuHealth.
func (in *DpuHealth) DeepCopy() *DpuHealth {
	if in == nil {
		return nil
	}
	out := new(DpuHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuInventory) DeepCopyInto(out *DpuInventory) {
	*out = *in
	if in.CPUCores != nil {
		in, out := &in.CPUCores, &out.CPUCores
		*out = new(int)
		**out = **in
	}
	if in.MemoryTotalBytes != nil {
		in, out := &in.MemoryTotalBytes, &out.MemoryTotalBytes
		*out = new(int64)
		**out = **in
	}
	if in.NetworkPorts != nil {
		in, out := &in.NetworkPorts, &out.NetworkPorts
		*out = make([]NetworkPortInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StorageDevices != nil {
		in, out := &in.StorageDevices, &out.StorageDevices
		*out = make([]StorageDeviceInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuInventory.
func (in *DpuInventory) DeepCopy() *DpuInventory {
	if in == nil {
		return nil
	}
	out := new(DpuInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuOperatorConfig) DeepCopyInto(out *DpuOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuOperatorConfig.
func (in *DpuOperatorConfig) DeepCopy() *DpuOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(DpuOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DpuOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuOperatorConfigList) DeepCopyInto(out *DpuOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DpuOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuOperatorConfigList.
func (in *DpuOperatorConfigList) DeepCopy() *DpuOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(DpuOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DpuOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuOperatorConfigSpec) DeepCopyInto(out *DpuOperatorConfigSpec) {
	*out = *in
	in.Generic.DeepCopyInto(&out.Generic)
	if in.VendorConfigs != nil {
		in, out := &in.VendorConfigs, &out.VendorConfigs
		*out = make([]VendorConfigEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PluginSelector != nil {
		in, out := &in.PluginSelector, &out.PluginSelector
		*out = new(PluginSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuOperatorConfigSpec.
func (in *DpuOperatorConfigSpec) DeepCopy() *DpuOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DpuOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuOperatorConfigStatus) DeepCopyInto(out *DpuOperatorConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActivePlugins != nil {
		in, out := &in.ActivePlugins, &out.ActivePlugins
		*out = make([]ActivePlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuOperatorConfigStatus.
func (in *DpuOperatorConfigStatus) DeepCopy() *DpuOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(DpuOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericConfig) DeepCopyInto(out *GenericConfig) {
	*out = *in
	if in.VFCount != nil {
		in, out := &in.VFCount, &out.VFCount
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericConfig.
func (in *GenericConfig) DeepCopy() *GenericConfig {
	if in == nil {
		return nil
	}
	out := new(GenericConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPortInfo) DeepCopyInto(out *NetworkPortInfo) {
	*out = *in
	if in.SpeedMbps != nil {
		in, out := &in.SpeedMbps, &out.SpeedMbps
		*out = new(int)
		**out = **in
	}
	if in.LinkUp != nil {
		in, out := &in.LinkUp, &out.LinkUp
		*out = new(bool)
		**out = **in
	}
	if in.SupportedModes != nil {
		in, out := &in.SupportedModes, &out.SupportedModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPortInfo.
func (in *NetworkPortInfo) DeepCopy() *NetworkPortInfo {
	if in == nil {
		return nil
	}
	out := new(NetworkPortInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginSelector) DeepCopyInto(out *PluginSelector) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Vendors != nil {
		in, out := &in.Vendors, &out.Vendors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginSelector.
func (in *PluginSelector) DeepCopy() *PluginSelector {
	if in == nil {
		return nil
	}
	out := new(PluginSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDeviceInfo) DeepCopyInto(out *StorageDeviceInfo) {
	*out = *in
	if in.CapacityBytes != nil {
		in, out := &in.CapacityBytes, &out.CapacityBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDeviceInfo.
func (in *StorageDeviceInfo) DeepCopy() *StorageDeviceInfo {
	if in == nil {
		return nil
	}
	out := new(StorageDeviceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorConfigEntry) DeepCopyInto(out *VendorConfigEntry) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorConfigEntry.
func (in *VendorConfigEntry) DeepCopy() *VendorConfigEntry {
	if in == nil {
		return nil
	}
	out := new(VendorConfigEntry)
	in.DeepCopyInto(out)
	return out
}
